py hello-world

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,13 @@
-#!/usr/bin/python3
-print("Best School")
+#!/bin/bash
+
+if [ -z "$PYFILE" ]; then
+  echo "Error: PYFILE environment variable is not set"
+  exit 1
+fi
+
+if [ ! -f "$PYFILE" ]; then
+  echo "Error: $PYFILE does not exist"
+  exit 1
+fi
+
+python3 "$PYFILE"
diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,2 +1,8 @@
-#!/usr/bin/python3
-print(f"Best School: {88+10}")
+#!/bin/bash
+
+if [ -z "$PYCODE" ]; then
+    echo "Error: PYCODE environment is not set"
+    exit 1
+fi
+
+python3 -c "$PYCODE"
